version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cloud_computing
      - POSTGRES_PASSWORD=defence1
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=defence1
    depends_on:
      - db